spring.config.import=optional:file:.env[.properties]

# Neon PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
aws.eventBridge.bus=default
AWS_REGION=eu-west-3
# HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/
spring.mvc.servlet.path=/


server.error.whitelabel.enabled=false

# Logging pour debug
logging.level.org.springframework.web=DEBUG
logging.level.com.example.demo=DEBUG